version: '2'

services:
    web:
        build: ./devops/nginx
        container_name: ${COMPOSE_PROJECT_NAME}_web
        ports:
            - ${NGINX_PORT}:80
        restart: always
        volumes:
            - ./volumes/nginx/logs:/var/log/nginx/
        volumes_from:
            - php
        depends_on:
            - php
    db:
        build:
            context: devops/mysql
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_db
        volumes:
            - db:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
    php:
        build:
            context: devops/php-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        container_name: ${COMPOSE_PROJECT_NAME}_php
        volumes:
            - ./:/var/www/html/
            - ${HOME}/.gitconfig:/home/www-data/.gitconfig
            - ${HOME}/.ssh:/home/www-data/.ssh
            - composer:/.composer/cache/
        depends_on:
            - db
    elasticsearch:
        build:
            context: devops/elk/elasticsearch
            args:
                ELK_VERSION: ${ELK_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data/
        environment:
            discovery.type: single-node
        ports:
            - ${ELASTICSEARCH_PORT}:9200
    logstash:
        build:
            context: devops/elk/logstash
            args:
                ELK_VERSION: ${ELK_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_logstash
        depends_on:
            - elasticsearch
    kibana:
        build:
            context: devops/elk/kibana
            args:
                ELK_VERSION: ${ELK_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_kibana
        ports:
            - ${KIBANA_PORT}:5601
        depends_on:
            - logstash

volumes:
    db:
    elasticsearch:
    composer: